### PR TITLE
styling-of-poll-sections

### PR DESCRIPTION
**Pull request by rickardinho**
Added bar charts to poll sections and general styling
Corrected icon on tabbar for profile

### CODE REVIEW

**Comment by heron2014** [comment]
Hi @rickardinho 

Good job on fixing pull request. We run your branch and have noticed couple of things. 

screen shot 2016-12-19 at 10 42 25

Is the Poll screen scrolling for you? 
We are running Iphone 6 simulator and the styling on When is cutting off the text? Is it cutting off the text on your simulator? 

Also when we run your branch we got minor error in regards to importing Intro component. In the router file the second line: ```import Intro from './components/Intro';```   - Intro should be lowercase and somehow was upper case.

If you could make these changes and push to this branch again that would be great! 

Thanks!

**Comment by rickardinho** [comment]
So, I noticed the intro import error, when i pulled from your master, so I had to change the "i" to uppercase or it wouldn't run as the file was named "Intro" in the master branch that I pulled (just checked master on Github and it is uppercase there too.

I tested on iphone 7 where it wasn't clipping the text due to the bigger screen.  I think as a lot of the screens are changing i might wait till its more developed before updating all the styling and making it responsive across all screens (and refactor to more common style elements across the app).  I will just make it so this text fits on smaller screens for now and re-push.

**Comment by heron2014** [comment]
@rickardinho makes sense!

**Comment by rickardinho** [comment]
just tried to commit some changes to styling branch and i got this error in github Desktop:
env: node: No such file or directory
 (1)

**Comment by rickardinho** [comment]
screen shot 2016-12-19 at 13 50 28

**Comment by rickardinho** [comment]
Also, I forgot to answer your question @heron2014 . No, the poll screen isn't scrolling (no scrollview component included in the event screens yet).  Feed scrolls as expect though.

**Comment by heron2014** [comment]
@rickardinho what node version are you running? We are on node 6.9.1

**Comment by rickardinho** [comment]
i'm running v 7.0.0

**Comment by heron2014** [comment]
It would be good that we're all running the same version of Node otherwise we might have some unexpected errors. Would it be possible for you to:
1. delete your `node_modules` folder 
2. install 6.9.1 (easiest way to use ```nvm``` https://github.com/creationix/nvm#install-script, which means you can use different version of node depending on project requirements)
3. run `npm install` 
Then see if you get the same error?

**Comment by rickardinho** [comment]
So i rolled back to node 6.9.1 but still getting the same problem.
Here's a longer error message:

2016-12-19 17:56:55.468 GitHub Desktop Login[1429:13662] AskPass with arguments: (
    "/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop Login",
    "Username for 'https://github.com': "
)
2016-12-19 17:56:55.519 GitHub Desktop Login[1430:13669] AskPass with arguments: (
    "/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop Login",
    "Password for 'https://d.rickardinho@gmail.com@github.com': "
)
env: node: No such file or directory
error: failed to push some refs to 'https://github.com/DRDD2016/sparkn2.git'
 (1)

**Comment by heron2014** [comment]
I think best would be to log your commits:
- git log
- see if there are duplication (time and date). They should be in reverse chronological order and should not repeat.  If there are duplication, let us know.

**Comment by rickardinho** [comment]
no duplication... see below

**Comment by rickardinho** [comment]
Davids-MacBook-Pro:sparkn2 dave$ git log
commit f179661592fc47edc930484fca7afc856b58da13
Author: rickardinho <d.rickardinho@gmail.com>
Date:   Mon Dec 19 10:13:49 2016 +0000

    styling-of-poll-sections
    
    Added bar charts to poll sections and general styling
    Corrected icon on tabbar for profile

commit cb2cc2ea88d507c46e07f1f73092a2aafe42f2bc
Merge: 6f73bb7 738ce32
Author: Mina <minaorangina@users.noreply.github.com>
Date:   Fri Dec 16 16:02:24 2016 +0000

    Merge pull request #46 from DRDD2016/remove-es2015
    
    chore: removes babel-es2015

commit 738ce326ce544f5d6e110819704409757bc45f52
Author: Anita <a.nita@hotmail.co.uk>
Date:   Fri Dec 16 15:59:27 2016 +0000

    chore: removes babel-es2015
:

**Comment by rickardinho** [comment]
i just tried it using the command line rather than github desktop and it seems to have worked, so i think its an issue with github desktop.  I'll use the command line instead.

**Comment by heron2014** [comment]
@rickardinho please let us know when this pull request is ready to merge.

**Comment by rickardinho** [comment]
So I have committed further changes, see "styling-poll-smallscreen" above.  Is this now part of this request or do I need to do a separate one?

**Comment by minaorangina** [comment]
@rickardinho Yes, this is all part of the same pull request.  If you don't plan to push anything else, we will review and merge 😄

**Comment by rickardinho** [comment]
Yea that's it for now. I think I will revisit the styling once the screens and screen layouts are all done, or settled down.

**Pull request merged**
